import { useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Grid, LinearProgress, Paper, Stack, TextField, Typography } from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CalendarTodayIcon from '@mui/icons-material/CalendarToday';
import api from '../api/api';
import Navbar from '../components/Navbar';
import { format, isValid } from 'date-fns';

const samples = ['Photosynthesis', 'TCP vs UDP', "Newton's Law", 'Derivative', 'Ionic Bond'];
const prompts = { Photosynthesis: 'How does photosynthesis work?', 'TCP vs UDP': 'What is the difference between TCP and UDP?', "Newton's Law": "Explain Newton's second law of motion.", Derivative: 'What is the derivative of x²?', 'Ionic Bond': 'What is an ionic bond?' };
const MAX_CHARS = 1000; const toPercent = value => Math.round(Math.max(0, Math.min(1, Number(value) || 0)) * 100);
const topicColor = { Biology:'#22C55E', Physics:'#2563EB', Chemistry:'#F59E0B', Mathematics:'#8B5CF6', 'Computer Science':'#2563EB', General:'#64748B' };
const prettyDate = value => { const date = value ? new Date(value) : null; return date && isValid(date) ? format(date, 'MMM dd, yyyy') : 'Recently'; };
const fallbackExplanation = topic => `Detected concepts related to ${String(topic || 'your question').toLowerCase()} and compared them with your saved study activity.`;

function SimilarCard({ item }) { const score = toPercent(item.score); return <Card elevation={0} sx={{ height:'100%' }}><CardContent sx={{ p:2.5 }}><Stack direction="row" justifyContent="space-between" spacing={1} alignItems="flex-start"><Chip label={`${score}% Similar`} size="small" color={score >= 80 ? 'success' : 'primary'} /><Typography variant="caption" color="text.secondary" sx={{ display:'flex', alignItems:'center', gap:.5 }}><CalendarTodayIcon sx={{ fontSize:13 }}/>{prettyDate(item.createdAt)}</Typography></Stack><Typography fontWeight={650} sx={{ mt:2, minHeight:48 }}>{item.content || item.question}</Typography><Chip label={item.topic || 'General'} size="small" sx={{ mt:2, bgcolor:'#F1F5F9', color:topicColor[item.topic] || topicColor.General }} /></CardContent></Card>; }

export default function AskQuestion() {
  const [content, setContent] = useState(''); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const remaining = MAX_CHARS - content.length; const over = remaining < 0; const similar = useMemo(() => result?.similarQuestions?.slice(0, 6) || [], [result]);
  const submit = async event => { event.preventDefault(); if (!content.trim() || over) return; setLoading(true); setError(''); setResult(null); try { const response = await api.post('/questions', { content: content.trim() }); setResult(response.data); setContent(''); } catch (err) { setError(err.response?.data?.message || 'We could not analyze that question. Please try again.'); } finally { setLoading(false); } };
  const topic = result?.question?.topic || 'General'; const confidence = toPercent(result?.confidenceScore);
  return <Box sx={{ minHeight:'100vh', pb:6, bgcolor:'background.default' }}><Navbar /><Container maxWidth={false} sx={{ maxWidth:'1400px', pt:{ xs:3, md:5 }, px:{ xs:2, md:3 } }}><Stack spacing={3}>
    <Box><Typography variant="h4">Ask a question</Typography><Typography color="text.secondary" sx={{ mt:1 }}>Get a topic prediction and discover related questions from your study history.</Typography></Box>
    <Paper elevation={0} sx={{ p:{ xs:2.5, md:3 }, border:'1px solid', borderColor:'divider' }}><Box component="form" onSubmit={submit}><TextField fullWidth multiline minRows={7} placeholder="What would you like to understand? Ask a study question in your own words..." value={content} onChange={event => setContent(event.target.value)} disabled={loading} error={over} inputProps={{ maxLength: MAX_CHARS + 1 }} sx={{ '& .MuiOutlinedInput-root': { p:2, alignItems:'flex-start' } }} /><Stack direction={{ xs:'column', sm:'row' }} justifyContent="space-between" spacing={2} alignItems={{ sm:'center' }} sx={{ mt:2 }}><Typography variant="caption" color={over ? 'error.main' : 'text.secondary'}>{over ? `Please remove ${Math.abs(remaining)} characters` : `${content.length}/${MAX_CHARS} characters`}</Typography><Button type="submit" variant="contained" disabled={loading || !content.trim() || over} startIcon={loading ? <CircularProgress size={17} color="inherit" /> : <SendIcon />}>{loading ? 'Analyzing question' : 'Analyze question'}</Button></Stack></Box></Paper>
    <Box><Typography variant="body2" fontWeight={700} sx={{ mb:1.25 }}>Quick examples</Typography><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap">{samples.map(sample => <Chip key={sample} label={sample} clickable variant="outlined" onClick={() => setContent(prompts[sample])} />)}</Stack></Box>
    {error && <Alert severity="error">{error}</Alert>}
    {result && <Stack spacing={3}><Paper elevation={0} sx={{ border:'1px solid', borderColor:'divider', overflow:'hidden' }}><Box sx={{ height:4, bgcolor:'primary.main' }} /><Box sx={{ p:{ xs:2.5, md:3 } }}><Stack direction={{ xs:'column', sm:'row' }} justifyContent="space-between" alignItems={{ sm:'center' }} spacing={2}><Box><Stack direction="row" spacing={1} alignItems="center"><AutoAwesomeIcon color="primary" fontSize="small" /><Typography variant="h6">Analysis result</Typography></Stack><Typography variant="body2" color="text.secondary" sx={{ mt:.75 }}>A concise classification based on the concepts in your question.</Typography></Box><Chip icon={<CheckCircleIcon />} label={`${confidence}% confidence`} color={confidence >= 75 ? 'success' : 'warning'} /></Stack><Grid container spacing={3} sx={{ mt:.5 }}><Grid size={{ xs:12, md:4 }}><Box sx={{ p:2, bgcolor:'#F8FAFC', borderRadius:1.5 }}><Typography variant="caption" color="text.secondary">TOPIC</Typography><Typography variant="h6" sx={{ mt:.75 }}>{topic}</Typography></Box></Grid><Grid size={{ xs:12, md:8 }}><Typography variant="caption" color="text.secondary">CONFIDENCE SCORE</Typography><Stack direction="row" justifyContent="space-between" sx={{ mt:.75, mb:1 }}><Typography variant="body2">Classification confidence</Typography><Typography fontWeight={700}>{confidence}%</Typography></Stack><LinearProgress variant="determinate" value={confidence} sx={{ height:8, borderRadius:4, bgcolor:'#E2E8F0' }} /><Typography variant="body2" color="text.secondary" sx={{ mt:2 }}>{result?.question?.explanation || result?.explanation || fallbackExplanation(topic)}</Typography></Grid></Grid></Box></Paper>
      <Box><Typography variant="h6" sx={{ mb:1 }}>Similar questions</Typography><Typography variant="body2" color="text.secondary" sx={{ mb:2.5 }}>Related questions from your study history.</Typography>{similar.length ? <Grid container spacing={2}>{similar.map((item,index) => <Grid key={item._id || item.id || index} size={{ xs:12, sm:6, lg:4 }}><SimilarCard item={item} /></Grid>)}</Grid> : <Paper elevation={0} sx={{ p:4, textAlign:'center', border:'1px dashed', borderColor:'divider' }}><Typography fontWeight={700}>No similar questions found yet.</Typography><Typography variant="body2" color="text.secondary" sx={{ mt:.5 }}>Keep asking questions to build your personal study archive.</Typography></Paper>}</Box>
    </Stack>}
  </Stack></Container></Box>;
}
